# 这是一个帮助您开始使用 Actions 的基础工作流
name: CI

# 控制工作流何时运行
on:
  # 在针对 main 分支的 push 或 pull request 事件时触发
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 允许您从 Actions 标签页手动运行此工作流
  workflow_dispatch:

# 一个工作流运行由一个或多个可以按顺序或并行运行的作业组成
jobs:
  # 此工作流包含一个名为 "build" 的作业
  build:
    # 作业将在其上运行的运行器类型
    runs-on: ubuntu-latest

    # 步骤代表将作为作业一部分执行的一系列任务
    steps:
      # 检出您的存储库到 $GITHUB_WORKSPACE，以便您的作业可以访问它
      - uses: actions/checkout@v4

      # 新增的步骤：运行 markdown 风格检查
      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent
          npx remark . --use remark-preset-lint-consistent --frail
